-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "Quest_status" (
	"id_quest_status" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Quest_status_id_quest_status_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"name" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Log" (
	"id_log" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Log_id_log_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"game_id" integer NOT NULL,
	"log_time" timestamp NOT NULL,
	"log_type" integer NOT NULL,
	"player_id" integer NOT NULL,
	"gameset_id" integer NOT NULL,
	"location_id" integer NOT NULL,
	"quest_id" integer,
	"quest_status" integer,
	"location_status" integer
);
--> statement-breakpoint
CREATE TABLE "Player" (
	"id_player" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Player_id_player_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"name" text NOT NULL,
	"play_name" text,
	"pass" text NOT NULL,
	"quest_lock" boolean NOT NULL,
	"quest_lock_endtime" timestamp,
	CONSTRAINT "Player_pass_key" UNIQUE("pass")
);
--> statement-breakpoint
CREATE TABLE "Locations" (
	"id_location" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Locations_id_location_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"gameset" integer NOT NULL,
	"name" text NOT NULL,
	"type" text NOT NULL,
	"gps" text NOT NULL,
	"map" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Log_type" (
	"id_log_type" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Log_type_id_log_type_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"name" text
);
--> statement-breakpoint
CREATE TABLE "Gameset" (
	"id_gameset" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Gameset_id_gameset_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Quests" (
	"id_quest" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Quests_id_quest_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"name" text NOT NULL,
	"description" text NOT NULL,
	"time_limit" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Location_status" (
	"id_quest_status" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Location_status_id_quest_status_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "log_type" (
	"id_log_type" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "log_type_id_log_type_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text
);
--> statement-breakpoint
CREATE TABLE "locations" (
	"id_location" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "locations_id_location_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"gameset_id" integer,
	"name" text NOT NULL,
	"type" text NOT NULL,
	"gps" text NOT NULL,
	"map" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "player" (
	"id_player" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "player_id_player_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"play_name" text,
	"pass" integer NOT NULL,
	"quest_lock" boolean DEFAULT false NOT NULL,
	"quest_lock_endtime" timestamp,
	CONSTRAINT "player_pass_key" UNIQUE("pass")
);
--> statement-breakpoint
CREATE TABLE "gameset" (
	"id_gameset" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gameset_id_gameset_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "game_session" (
	"id_game_session" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "game_session_id_game_session_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"start_time" timestamp NOT NULL,
	"duration" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "log" (
	"id_log" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "log_id_log_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"game_id" integer NOT NULL,
	"log_time" timestamp DEFAULT now() NOT NULL,
	"log_type_id" integer NOT NULL,
	"player_id" integer NOT NULL,
	"gameset_id" integer NOT NULL,
	"location_id" integer NOT NULL,
	"quest_id" integer,
	"quest_status_id" integer,
	"location_status_id" integer
);
--> statement-breakpoint
CREATE TABLE "quests" (
	"id_quest" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "quests_id_quest_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text NOT NULL,
	"time_limit" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "quest_status" (
	"id_quest_status" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "quest_status_id_quest_status_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "location_status" (
	"id_location_status" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "location_status_id_location_status_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Gameset_Locations" (
	"Gameset_id_gameset" integer NOT NULL,
	"Locations_gameset" integer NOT NULL,
	CONSTRAINT "Gameset_Locations_pkey" PRIMARY KEY("Gameset_id_gameset","Locations_gameset")
);
--> statement-breakpoint
CREATE TABLE "gameset_locations" (
	"gameset_id" integer NOT NULL,
	"location_id" integer NOT NULL,
	CONSTRAINT "gameset_locations_pkey" PRIMARY KEY("gameset_id","location_id")
);
--> statement-breakpoint
ALTER TABLE "Log" ADD CONSTRAINT "Log_quest_status_fkey" FOREIGN KEY ("quest_status") REFERENCES "public"."Quest_status"("id_quest_status") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Log" ADD CONSTRAINT "Log_log_type_fkey" FOREIGN KEY ("log_type") REFERENCES "public"."Log_type"("id_log_type") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Log" ADD CONSTRAINT "Log_player_id_fkey" FOREIGN KEY ("player_id") REFERENCES "public"."Player"("id_player") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Log" ADD CONSTRAINT "Log_gameset_id_fkey" FOREIGN KEY ("gameset_id") REFERENCES "public"."Gameset"("id_gameset") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Log" ADD CONSTRAINT "Log_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "public"."Locations"("id_location") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Log" ADD CONSTRAINT "Log_quest_id_fkey" FOREIGN KEY ("quest_id") REFERENCES "public"."Quests"("id_quest") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Log" ADD CONSTRAINT "Log_quest_status_fkey1" FOREIGN KEY ("quest_status") REFERENCES "public"."Quest_status"("id_quest_status") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Log" ADD CONSTRAINT "Log_location_status_fkey" FOREIGN KEY ("location_status") REFERENCES "public"."Location_status"("id_quest_status") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Log" ADD CONSTRAINT "Log_log_type_fkey1" FOREIGN KEY ("log_type") REFERENCES "public"."Log_type"("id_log_type") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Log" ADD CONSTRAINT "Log_player_id_fkey1" FOREIGN KEY ("player_id") REFERENCES "public"."Player"("id_player") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Log" ADD CONSTRAINT "Log_gameset_id_fkey1" FOREIGN KEY ("gameset_id") REFERENCES "public"."Gameset"("id_gameset") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Log" ADD CONSTRAINT "Log_location_id_fkey1" FOREIGN KEY ("location_id") REFERENCES "public"."Locations"("id_location") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Log" ADD CONSTRAINT "Log_quest_id_fkey1" FOREIGN KEY ("quest_id") REFERENCES "public"."Quests"("id_quest") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Log" ADD CONSTRAINT "Log_quest_status_fkey2" FOREIGN KEY ("quest_status") REFERENCES "public"."Quest_status"("id_quest_status") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Log" ADD CONSTRAINT "Log_location_status_fkey1" FOREIGN KEY ("location_status") REFERENCES "public"."Location_status"("id_quest_status") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "log" ADD CONSTRAINT "log_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."game_session"("id_game_session") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "log" ADD CONSTRAINT "log_log_type_id_fkey" FOREIGN KEY ("log_type_id") REFERENCES "public"."log_type"("id_log_type") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "log" ADD CONSTRAINT "log_player_id_fkey" FOREIGN KEY ("player_id") REFERENCES "public"."player"("id_player") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "log" ADD CONSTRAINT "log_gameset_id_fkey" FOREIGN KEY ("gameset_id") REFERENCES "public"."gameset"("id_gameset") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "log" ADD CONSTRAINT "log_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id_location") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "log" ADD CONSTRAINT "log_quest_id_fkey" FOREIGN KEY ("quest_id") REFERENCES "public"."quests"("id_quest") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "log" ADD CONSTRAINT "log_quest_status_id_fkey" FOREIGN KEY ("quest_status_id") REFERENCES "public"."quest_status"("id_quest_status") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "log" ADD CONSTRAINT "log_location_status_id_fkey" FOREIGN KEY ("location_status_id") REFERENCES "public"."location_status"("id_location_status") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Gameset_Locations" ADD CONSTRAINT "Gameset_Locations_Gameset_id_gameset_fkey" FOREIGN KEY ("Gameset_id_gameset") REFERENCES "public"."Gameset"("id_gameset") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Gameset_Locations" ADD CONSTRAINT "Gameset_Locations_Gameset_id_gameset_fkey1" FOREIGN KEY ("Gameset_id_gameset") REFERENCES "public"."Gameset"("id_gameset") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gameset_locations" ADD CONSTRAINT "gameset_locations_gameset_id_fkey" FOREIGN KEY ("gameset_id") REFERENCES "public"."gameset"("id_gameset") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gameset_locations" ADD CONSTRAINT "gameset_locations_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id_location") ON DELETE no action ON UPDATE no action;
*/