CREATE TABLE "player_role" (
	"id_player_role" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "player_role_id_player_role_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "location" DROP CONSTRAINT "location_type_quest_type_id_quest_type_fk";
--> statement-breakpoint
ALTER TABLE "game_session" ALTER COLUMN "id_game_session" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "game_session" ALTER COLUMN "id_game_session" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "game_session_id_game_session_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "location" ALTER COLUMN "id_location" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "location" ALTER COLUMN "id_location" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "location_id_location_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "log_type" ALTER COLUMN "id_log_type" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "log_type" ALTER COLUMN "id_log_type" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "log_type_id_log_type_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "log" ALTER COLUMN "id_log" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "log" ALTER COLUMN "id_log" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "log_id_log_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "log" ALTER COLUMN "location_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "player_progress" ALTER COLUMN "id_progress" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "player_progress" ALTER COLUMN "id_progress" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "player_progress_id_progress_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "player" ALTER COLUMN "id_player" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "player" ALTER COLUMN "id_player" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "player_id_player_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "privilege_level" ALTER COLUMN "id_privilege_level" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "privilege_level" ALTER COLUMN "id_privilege_level" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "privilege_level_id_privilege_level_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "quest_status" ALTER COLUMN "id_quest_status" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "quest_status" ALTER COLUMN "id_quest_status" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "quest_status_id_quest_status_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "quest_type" ALTER COLUMN "id_quest_type" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "quest_type" ALTER COLUMN "id_quest_type" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "quest_type_id_quest_type_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "quests" ALTER COLUMN "id_quest" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "quests" ALTER COLUMN "id_quest" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "quests_id_quest_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "team" ALTER COLUMN "id_team" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "team" ALTER COLUMN "id_team" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "team_id_team_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "location" ADD COLUMN "type_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "location" ADD COLUMN "gps" text NOT NULL;--> statement-breakpoint
ALTER TABLE "location" ADD COLUMN "completed" boolean DEFAULT false;--> statement-breakpoint
ALTER TABLE "log" ADD COLUMN "caught_player_id" integer;--> statement-breakpoint
ALTER TABLE "player" ADD COLUMN "role_id" integer;--> statement-breakpoint
ALTER TABLE "player" ADD COLUMN "points" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "player" ADD COLUMN "bubble_burst_time" timestamp;--> statement-breakpoint
ALTER TABLE "player" ADD COLUMN "runner_shield_time" timestamp;--> statement-breakpoint
ALTER TABLE "player" ADD COLUMN "quest_end_time" timestamp;--> statement-breakpoint
ALTER TABLE "quests" ADD COLUMN "players_required" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "team" ADD COLUMN "points" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "team" ADD COLUMN "map" text;--> statement-breakpoint
ALTER TABLE "team" ADD COLUMN "life360" text;--> statement-breakpoint
ALTER TABLE "location" ADD CONSTRAINT "location_type_id_quest_type_id_quest_type_fk" FOREIGN KEY ("type_id") REFERENCES "public"."quest_type"("id_quest_type") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "log" ADD CONSTRAINT "log_caught_player_id_player_id_player_fk" FOREIGN KEY ("caught_player_id") REFERENCES "public"."player"("id_player") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player" ADD CONSTRAINT "player_role_id_player_role_id_player_role_fk" FOREIGN KEY ("role_id") REFERENCES "public"."player_role"("id_player_role") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "location" DROP COLUMN "type";--> statement-breakpoint
ALTER TABLE "location" DROP COLUMN "latitude";--> statement-breakpoint
ALTER TABLE "location" DROP COLUMN "map";