DROP TABLE IF EXISTS "log" CASCADE;
DROP TABLE IF EXISTS "gameset_locations" CASCADE;
DROP TABLE IF EXISTS "game_session" CASCADE;
DROP TABLE IF EXISTS "location_status" CASCADE;
DROP TABLE IF EXISTS "quest_status" CASCADE;
DROP TABLE IF EXISTS "quests" CASCADE;
DROP TABLE IF EXISTS "log_type" CASCADE;
DROP TABLE IF EXISTS "player" CASCADE;
DROP TABLE IF EXISTS "gameset" CASCADE;
DROP TABLE IF EXISTS "locations" CASCADE;
DROP TABLE IF EXISTS "Log" CASCADE;
DROP TABLE IF EXISTS "Gameset_Locations" CASCADE;
DROP TABLE IF EXISTS "Game_Session" CASCADE;
DROP TABLE IF EXISTS "Location_Status" CASCADE;
DROP TABLE IF EXISTS "Quest_Status" CASCADE;
DROP TABLE IF EXISTS "Quests" CASCADE;
DROP TABLE IF EXISTS "Log_Type" CASCADE;
DROP TABLE IF EXISTS "Player" CASCADE;
DROP TABLE IF EXISTS "Gameset" CASCADE;
DROP TABLE IF EXISTS "Locations" CASCADE;

CREATE TABLE gameset (
  id_gameset INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  name text NOT NULL
);

CREATE TABLE locations (
  id_location INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  gameset_id int, 
  name text NOT NULL,
  type text NOT NULL,
  gps text NOT NULL,
  map text NOT NULL
);

CREATE TABLE player (
  id_player INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  name text NOT NULL,
  play_name text,
  pass int UNIQUE NOT NULL, 
  quest_lock bool NOT NULL DEFAULT false,
  quest_lock_endtime timestamp
);

CREATE TABLE log_type (
  id_log_type INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  name text
);

CREATE TABLE quests (
  id_quest INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  name text NOT NULL,
  description text NOT NULL,
  time_limit int NOT NULL
);

CREATE TABLE quest_status (
  id_quest_status INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  name text NOT NULL 
);

CREATE TABLE location_status (
  id_location_status INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, 
  name text NOT NULL
);

CREATE TABLE game_session (
  id_game_session INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  start_time timestamp NOT NULL, 
  duration int NOT NULL
);

CREATE TABLE log (
  id_log INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  game_id int NOT NULL,
  log_time timestamp NOT NULL DEFAULT now(),
  log_type_id int NOT NULL,
  player_id int NOT NULL,
  gameset_id int NOT NULL,
  location_id int NOT NULL,
  quest_id int,
  quest_status_id int,
  location_status_id int
);

COMMENT ON COLUMN quests.time_limit IS 'v sekundách';
COMMENT ON COLUMN game_session.duration IS 'v sekundách';

CREATE TABLE gameset_locations (
  gameset_id int NOT NULL,
  location_id int NOT NULL,
  PRIMARY KEY (gameset_id, location_id)
);

ALTER TABLE gameset_locations ADD FOREIGN KEY (gameset_id) REFERENCES gameset (id_gameset);
ALTER TABLE gameset_locations ADD FOREIGN KEY (location_id) REFERENCES locations (id_location);

ALTER TABLE log ADD FOREIGN KEY (game_id) REFERENCES game_session (id_game_session);
ALTER TABLE log ADD FOREIGN KEY (log_type_id) REFERENCES log_type (id_log_type);
ALTER TABLE log ADD FOREIGN KEY (player_id) REFERENCES player (id_player);
ALTER TABLE log ADD FOREIGN KEY (gameset_id) REFERENCES gameset (id_gameset);
ALTER TABLE log ADD FOREIGN KEY (location_id) REFERENCES locations (id_location);
ALTER TABLE log ADD FOREIGN KEY (quest_id) REFERENCES quests (id_quest);
ALTER TABLE log ADD FOREIGN KEY (quest_status_id) REFERENCES quest_status (id_quest_status);
ALTER TABLE log ADD FOREIGN KEY (location_status_id) REFERENCES location_status (id_location_status);